// Code generated by tools/gen-contract from wsproto.schema.json and rest.schema.json; DO NOT EDIT (#3439).
// Global types for tsc --checkJs (tsconfig.json beside it); never served.
export {};

declare global {
  interface AgentMetaPatch {
    duration_ms?: number;
    last_detail?: string;
    last_tool?: string;
    tool_uses?: number;
  }
  interface AskQuestion {
    items: AskQuestionItem[];
    tool_use_id: string;
  }
  interface AskQuestionItem {
    header?: string;
    multi_select?: boolean;
    options: AskQuestionOpt[];
    question: string;
  }
  interface AskQuestionOpt {
    description?: string;
    label: string;
  }
  interface ChatBinding {
    chat_id: string;
    chat_type?: string;
    platform: string;
  }
  interface CodeChange {
    action?: string;
    branch?: string;
    identifier?: string;
    provider?: string;
    repo?: string;
    url: string;
  }
  interface Counts {
    done: number;
    failed: number;
    queued: number;
    running: number;
    skipped: number;
    stopped: number;
    total: number;
  }
  interface Diag {
    action: string;
    key: string;
    layer: string;
    reason: string;
  }
  interface EventEntry {
    ask_question?: AskQuestion;
    background?: boolean;
    cost?: number;
    detail?: string;
    duration_ms?: number;
    image_paths?: string[];
    images?: string[];
    last_tool?: string;
    status?: string;
    subagent?: string;
    summary?: string;
    task_id?: string;
    team_name?: string;
    time: number;
    tokens?: number;
    tool?: string;
    tool_call?: ToolCall;
    tool_use_id?: string;
    tool_uses?: number;
    type: 'user' | 'text' | 'thinking' | 'tool_use' | 'tool_result' | 'agent' | 'todo' | 'ask_question' | 'task_start' | 'task_progress' | 'task_done' | 'result' | 'system' | 'persist_gap';
    uuid?: string;
  }
  interface MeteringEntry {
    unit: string;
    unit_plural?: string;
    value: number;
  }
  interface OverlayFieldDrift {
    current: string;
    field: string;
    stored: string;
  }
  interface ProjectConfig {
    access_profile?: string;
    backend?: string;
    chat_bindings?: ChatBinding[];
    created_at?: number;
    display_name?: string;
    emoji?: string;
    favorite?: boolean;
    git_remote?: string;
    git_sync: boolean;
    memory_file?: string;
    planner_model?: string;
    planner_prompt?: string;
  }
  interface RecentSession {
    last_active: number;
    last_prompt?: string;
    project?: string;
    retired_at?: number;
    session_id: string;
    summary?: string;
    workspace?: string;
  }
  interface SessionSnapshot {
    access_profile?: string;
    agent: string;
    backend?: string;
    chat_id?: string;
    chat_type?: string;
    cli_name?: string;
    cli_version?: string;
    code_changes?: CodeChange[];
    context_usage_percent?: number;
    cost_unit?: string;
    created_at?: number;
    death_detail?: string;
    death_reason?: string;
    effort?: string;
    is_planner?: boolean;
    key: string;
    label_origin?: string;
    last_active: number;
    last_activity?: string;
    last_prompt?: string;
    last_response?: string;
    message_count?: number;
    metering_usage?: MeteringEntry[];
    model?: string;
    node?: string;
    overlay_drift: OverlayFieldDrift[];
    platform: string;
    project?: string;
    project_fallback?: boolean;
    protocol: string;
    session_id: string;
    spawn_diags: Diag[];
    startup_failure?: StartupFailureView;
    state: string;
    subagents?: SubagentInfo[];
    summary?: string;
    total_cost: number;
    tuning_effort?: string;
    tuning_model?: string;
    turn_duration_ms?: number;
    user_label?: string;
    workflows?: Summary[];
    workspace?: string;
  }
  interface StartupFailureView {
    class?: string;
    new_session?: boolean;
    retry_at?: number;
    streak?: number;
  }
  interface SubagentInfo {
    activity?: string;
    background?: boolean;
    duration_ms?: number;
    internal_agent_id?: string;
    last_detail?: string;
    last_tool?: string;
    name: string;
    started_at_ms?: number;
    status?: string;
    task_id?: string;
    task_type?: string;
    tool_use_id?: string;
    tool_uses?: number;
  }
  interface Summary {
    counts: Counts;
    current_phase?: string;
    ended_at?: number;
    epoch: string;
    name?: string;
    started_at?: number;
    status: string;
    task_id: string;
    tokens?: number;
    version: number;
  }
  interface ToolCall {
    id: string;
    input_json?: string;
    kind?: string;
    name?: string;
    output_json?: string;
    status?: string;
    title?: string;
  }
  interface projectListEntry {
    config: ProjectConfig;
    created_at?: number;
    dir_mtime?: number;
    favorite?: boolean;
    git_remote_url?: string;
    github?: boolean;
    name: string;
    node: string;
    path: string;
    stableKey?: string;
  }
  interface sessionStats {
    active: number;
    agents: string[];
    backend: string;
    cli_name: string;
    cli_version: string;
    default_workspace: string;
    history_tag?: string;
    max_procs: number;
    projects: projectListEntry[];
    ready: number;
    running: number;
    system: Record<string, unknown>;
    total: number;
    uptime: string;
    version: number;
    version_tag?: string;
    watchdog: watchdogStats;
    workspace_id: string;
    workspace_name: string;
  }
  interface watchdogStats {
    no_output_kills: number;
    total_kills: number;
  }
  interface WsFrame_agent_done {
    type: 'agent_done';
    key?: string;
    status?: string;
    task_id?: string;
  }
  interface WsFrame_agent_event {
    type: 'agent_event';
    event?: EventEntry;
    key?: string;
    task_id?: string;
  }
  interface WsFrame_agent_meta {
    type: 'agent_meta';
    key?: string;
    meta?: AgentMetaPatch;
    task_id?: string;
  }
  interface WsFrame_agent_subscribe_rejected {
    type: 'agent_subscribe_rejected';
    key?: string;
    reason?: string;
    task_id?: string;
  }
  interface WsFrame_auth_fail {
    type: 'auth_fail';
    error?: string;
    retry_after?: number;
  }
  interface WsFrame_auth_ok {
    type: 'auth_ok';
    asset_version?: string;
  }
  interface WsFrame_error {
    type: 'error';
    error?: string;
    key?: string;
    node?: string;
  }
  interface WsFrame_event {
    type: 'event';
    event?: EventEntry;
    key?: string;
    node?: string;
  }
  interface WsFrame_history {
    type: 'history';
    events?: EventEntry[];
    has_more?: boolean;
    initial?: boolean;
    key?: string;
    node?: string;
  }
  interface WsFrame_interrupt_ack {
    type: 'interrupt_ack';
    error?: string;
    id?: string;
    key?: string;
    node?: string;
    status?: string;
  }
  interface WsFrame_pong {
    type: 'pong';
  }
  interface WsFrame_run_ended {
    type: 'run_ended';
    duration_ms?: number;
    ended_at?: number;
    error_class?: string;
    error_msg?: string;
    owner_id: string;
    run_id: string;
    session_id?: string;
    started_at?: number;
    state: string;
    subsystem: string;
    trigger?: string;
  }
  interface WsFrame_run_started {
    type: 'run_started';
    fresh?: boolean;
    owner_id: string;
    run_id: string;
    session_id?: string;
    started_at: number;
    subsystem: string;
    trigger?: string;
  }
  interface WsFrame_send_ack {
    type: 'send_ack';
    error?: string;
    id?: string;
    key?: string;
    node?: string;
    status?: string;
  }
  interface WsFrame_send_error {
    type: 'send_error';
    error?: string;
    key?: string;
    node?: string;
  }
  interface WsFrame_session_state {
    type: 'session_state';
    key?: string;
    node?: string;
    reason?: string;
    state?: string;
  }
  interface WsFrame_sessions_update {
    type: 'sessions_update';
  }
  interface WsFrame_subscribed {
    type: 'subscribed';
    key?: string;
    node?: string;
    reason?: string;
    state?: string;
  }
  interface WsFrame_unsubscribed {
    type: 'unsubscribed';
    key?: string;
    node?: string;
  }
  interface WsFrames {
    agent_done: WsFrame_agent_done;
    agent_event: WsFrame_agent_event;
    agent_meta: WsFrame_agent_meta;
    agent_subscribe_rejected: WsFrame_agent_subscribe_rejected;
    auth_fail: WsFrame_auth_fail;
    auth_ok: WsFrame_auth_ok;
    error: WsFrame_error;
    event: WsFrame_event;
    history: WsFrame_history;
    interrupt_ack: WsFrame_interrupt_ack;
    pong: WsFrame_pong;
    run_ended: WsFrame_run_ended;
    run_started: WsFrame_run_started;
    send_ack: WsFrame_send_ack;
    send_error: WsFrame_send_error;
    session_state: WsFrame_session_state;
    sessions_update: WsFrame_sessions_update;
    subscribed: WsFrame_subscribed;
    unsubscribed: WsFrame_unsubscribed;
  }
  interface RestResponse_sessions {
    sessions: SessionSnapshot[];
    stats: sessionStats;
  }
  interface RestResponse_sessions_history {
    history_sessions: RecentSession[];
    history_tag?: string;
  }
  interface RestResponse_sessions_multi {
    nodes: Record<string, unknown>;
    sessions: unknown[];
    stats: sessionStats;
  }
  interface RestResponses {
    sessions: RestResponse_sessions;
    sessions_history: RestResponse_sessions_history;
    sessions_multi: RestResponse_sessions_multi;
  }
}
