package server

import (
	"strings"
	"testing"
)

// TestIsValidAnonCookieValue covers the format gate added by R236-SEC-06
// (#485). mintAnonCookie always emits 32 lowercase-hex chars; any other
// shape originated outside the server and must be rejected so the
// uploadOwner bucket is rooted in server-generated bytes.
func TestIsValidAnonCookieValue(t *testing.T) {
	cases := []struct {
		name string
		v    string
		want bool
	}{
		{"empty", "", false},
		{"too_short", strings.Repeat("a", 31), false},
		{"too_long", strings.Repeat("a", 33), false},
		{"valid_lowercase_hex", "0123456789abcdef0123456789abcdef", true},
		{"uppercase_rejected", "0123456789ABCDEF0123456789ABCDEF", false},
		{"with_g", strings.Repeat("g", 32), false},
		{"with_space", "0123456789abcdef0123456789abcde ", false},
		{"with_newline", "0123456789abcdef0123456789abcde\n", false},
		{"all_zeros", strings.Repeat("0", 32), true},
		{"all_fs", strings.Repeat("f", 32), true},
		{"unicode", "0123456789abcdef0123456789abcdé", false},
	}
	for _, c := range cases {
		if got := isValidAnonCookieValue(c.v); got != c.want {
			t.Errorf("isValidAnonCookieValue(%q) = %v, want %v", c.v, got, c.want)
		}
	}
}
