package server

import (
	"context"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/naozhi/naozhi/internal/cli"
	"github.com/naozhi/naozhi/internal/dashboard/auth"
	dashproject "github.com/naozhi/naozhi/internal/dashboard/project"
	"github.com/naozhi/naozhi/internal/osutil"
	"github.com/naozhi/naozhi/internal/session"
)

// Upload size ceilings. The PDF cap honours Anthropic's 32 MB document-block
// limit so a file accepted here is not later rejected by the API; both values
// match the byte counts announced to the user.
const (
	maxImageBytes = 10 << 20 // 10 MB
	maxPDFBytes   = 32 << 20 // 32 MB (Anthropic API limit)

	// uploadBodyBytes bounds the multipart envelope for /api/sessions/upload:
	// maxPDFBytes + ~2 MB multipart overhead.
	uploadBodyBytes = maxPDFBytes + (2 << 20)

	// maxMultipartFields caps non-file form fields per multipart request:
	// net/http allows ~1000 Value entries, so a padded body could inflate the
	// in-memory Value map without exceeding our byte cap.
	maxMultipartFields = 32
)

// rejectIfTooManyFields returns true (and writes a 400) when the
// multipart form carries more than maxMultipartFields non-file entries.
// Callers must invoke this immediately after ParseMultipartForm and bail
// out on a true return. File uploads are counted separately by the
// caller-specific "files"/"file" slice length checks.
func rejectIfTooManyFields(w http.ResponseWriter, r *http.Request) bool {
	if r.MultipartForm == nil {
		return false
	}
	total := 0
	for _, vs := range r.MultipartForm.Value {
		total += len(vs)
		if total > maxMultipartFields {
			writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "too many form fields"})
			return true
		}
	}
	return false
}

// SendHandler serves the HTTP send API, delegating to Hub for local sends.
// router is the SendRouter view of *session.Router (consumer.go); wiring
// passes hub.router, tests may inject a stub.
type SendHandler struct {
	nodeAccess    NodeAccessor
	hub           *Hub
	router        SendRouter
	uploadStore   *uploadStore
	uploadLimiter *ipLimiter     // per-IP upload rate limiter (10/min)
	sendLimiter   *ipLimiter     // per-IP send rate limiter (30/min)
	auth          *auth.Handlers // for isSecure(r) when minting the nz_anon cookie in no-token mode
	trustedProxy  bool           // whether to trust X-Forwarded-For for client IP
	orient        *orientConfig  // image auto-orientation; nil = feature off
}

// uploadOwner derives a stable owner key from the auth cookie, Bearer token,
// or (no-token mode) a per-browser nz_anon cookie, so co-NAT User B cannot
// claim User A's upload via TakeAll. ok=false means no per-browser key could
// be derived (every credential absent AND mintAnonCookie failed); callers
// MUST respond 503 rather than fall back to an IP-derived bucket (#501).
func uploadOwner(w http.ResponseWriter, r *http.Request, ah *auth.Handlers, trustedProxy bool) (string, bool) {
	// Honour the auth cookie only when it matches the current cookieMAC
	// (constant-time): a Bearer caller with a forged nz_auth cookie must not
	// bucket-shift onto another owner key. nil auth or empty MAC (no-token
	// mode) skips the branch — fail closed (#1399).
	if c, err := r.Cookie(auth.AuthCookieName); err == nil && c.Value != "" && ah != nil {
		if mac := ah.CookieMAC(); mac != "" &&
			subtle.ConstantTimeCompare([]byte(c.Value), []byte(mac)) == 1 {
			return ownerKeyFromCookie(c.Value), true
		}
	}
	if bearer := r.Header.Get("Authorization"); strings.HasPrefix(bearer, "Bearer ") {
		if token := strings.TrimPrefix(bearer, "Bearer "); token != "" {
			// 128-bit, matching ownerKeyFromCookie.
			sum := sha256.Sum256([]byte(token))
			return hex.EncodeToString(sum[:16]), true
		}
	}
	// Trust the cookie only in mintAnonCookie's wire shape; anything else
	// re-mints so the bucket is always rooted in server-generated bytes
	// (#485). wsDeriveUploadOwner applies the same gate.
	if c, err := r.Cookie(anonCookieName); err == nil && isValidAnonCookieValue(c.Value) {
		return renewedOwnerFromCookie(w, r, ah, c.Value), true
	}
	if w != nil {
		val, err := mintAnonCookie(w, r, ah)
		if err == nil {
			return ownerKeyFromCookie(val), true
		}
		slog.Warn("uploadOwner: mintAnonCookie failed; refusing to fall back to IP-derived owner key", "err", err)
	}
	// No clientIP fallback: co-NAT browsers would share a bucket, reopening
	// the TakeAll cross-tenant window (#501).
	return "", false
}

// uploadOwnerOrFail wraps uploadOwner with the standard 503 response so
// individual handlers don't repeat the writeJSONStatus boilerplate. Returns
// owner + ok=true when a real per-browser key was minted/recovered; on
// ok=false the caller MUST stop processing — the response has already been
// written.
func uploadOwnerOrFail(w http.ResponseWriter, r *http.Request, ah *auth.Handlers, trustedProxy bool) (string, bool) {
	owner, ok := uploadOwner(w, r, ah, trustedProxy)
	if !ok {
		// 30s Retry-After mirrors the rate-limiter convention.
		w.Header().Set("Retry-After", "30")
		writeJSONStatus(w, http.StatusServiceUnavailable, map[string]string{"error": "could not derive upload owner; please retry"})
	}
	return owner, ok
}

// resolveAttachmentWorkspace picks the validated absolute path to write
// file_ref attachments under for the given session key: an explicit
// reqWorkspace if the request carries one, else the live session's
// Workspace(), else the router's saved workspace for the chat key (the
// dashboard does not re-announce the workspace on every send). Returns
// validateWorkspace's generic client-facing error on rejection.
func resolveAttachmentWorkspace(hub *Hub, sessionKey, reqWorkspace string) (string, error) {
	// Hot path: client announced a workspace — trust but validate it.
	if reqWorkspace != "" {
		return validateWorkspace(reqWorkspace, hub.allowedRoot)
	}
	// Prefer the live session's Workspace() (the CLI's actual cwd). The
	// router lookup takes the chat-key prefix — the ":<agent>" suffix is not
	// part of the workspace override key.
	var ws string
	if sess := hub.router.SessionFor(sessionKey); sess != nil {
		ws = sess.Workspace()
	}
	if ws == "" {
		chatKey := sessionKey
		if idx := strings.LastIndexByte(sessionKey, ':'); idx > 0 {
			chatKey = sessionKey[:idx]
		}
		ws = hub.router.Workspace(chatKey)
	}
	if ws == "" {
		return "", fmt.Errorf("workspace is not a valid directory")
	}
	// Revalidate against allowedRoot: a saved workspace may predate a
	// tightened allowedRoot.
	return validateWorkspace(ws, hub.allowedRoot)
}

// handleUpload accepts a single image OR PDF file and stores it for later
// reference by file_ids. PDFs are held in memory until the matching send
// call, at which point they are persisted into the session workspace so
// Claude can read them via its native Read tool (images remain inline).
// POST /api/sessions/upload  (multipart/form-data, field "file")
// Response: {"id": "<hex>", "kind": "image_inline"|"file_ref", "size": <bytes>, "name": "..."}
func (h *SendHandler) handleUpload(w http.ResponseWriter, r *http.Request) {
	if h.uploadLimiter != nil && !h.uploadLimiter.AllowRequest(r) {
		writeJSONStatus(w, http.StatusTooManyRequests, map[string]string{"error": "upload rate limit exceeded"})
		return
	}
	// PDF cap dominates the body size. MaxBytesReader gives a clean 413
	// rather than the opaque "bad multipart form" that ParseMultipartForm
	// returns when the body exceeds its own limit.
	r.Body = http.MaxBytesReader(w, r.Body, int64(uploadBodyBytes))
	if err := r.ParseMultipartForm(int64(uploadBodyBytes)); err != nil {
		// Don't echo stdlib internals (boundary details, file-system paths)
		// back to the client; log internally for operator triage.
		slog.Warn("upload: multipart parse failed", "err", err)
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "bad multipart form"})
		return
	}
	if rejectIfTooManyFields(w, r) {
		return
	}
	files := r.MultipartForm.File["file"]
	if len(files) != 1 {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "exactly one file required"})
		return
	}
	att, err := parseAttachmentFile(files[0], true)
	if err != nil {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}
	owner, ok := uploadOwnerOrFail(w, r, h.auth, h.trustedProxy)
	if !ok {
		return
	}
	id, err := h.uploadStore.Put(owner, att)
	if err != nil {
		// Distinguish per-owner quota from global exhaustion so the client
		// can show "你上传的文件过多" vs a generic "服务繁忙" prompt.
		msg := "too many pending uploads"
		if errors.Is(err, errUploadPerOwner) {
			msg = "upload quota exceeded for this user"
		}
		writeJSONStatus(w, http.StatusTooManyRequests, map[string]string{"error": msg})
		return
	}
	// Echo kind + size + name so the frontend can render a PDF chip vs an
	// image thumbnail without a second round-trip.
	writeJSON(w, map[string]any{
		"id":   id,
		"kind": att.Kind,
		"size": att.Size,
		"name": att.OrigName,
		"mime": att.MimeType,
	})
}

func (h *SendHandler) handleSend(w http.ResponseWriter, r *http.Request) {
	if h.sendLimiter != nil && !h.sendLimiter.AllowRequest(r) {
		writeJSONStatus(w, http.StatusTooManyRequests, map[string]string{"error": sendRateLimitedMsg})
		return
	}

	var key, text, node, workspace, resumeID, backend, accessProfile string
	var images []cli.Attachment
	var fileIDs []string

	ct := r.Header.Get("Content-Type")
	if strings.HasPrefix(ct, "multipart/form-data") {
		// Inline multipart uploads bypass the uploadStore per-owner quota;
		// gate them behind the dedicated uploadLimiter so a burst of
		// multipart sends can't slip past at the (looser) sendLimiter rate.
		// Without this, 30 req/min × 5 files × 10 MB = 1.5 GB/min of inline
		// file bytes would be funneled into CLI stdin.
		if h.uploadLimiter != nil && !h.uploadLimiter.AllowRequest(r) {
			writeJSONStatus(w, http.StatusTooManyRequests, map[string]string{"error": uploadRateLimitedMsg})
			return
		}
		// Shrink body cap to 22 MB (2× max inline file 10 MB + form overhead)
		// and drop inline fan-out from 5→2 so authenticated users uploading
		// many attachments per turn must route through /api/sessions/upload
		// which enforces maxUploadPerOwner.
		r.Body = http.MaxBytesReader(w, r.Body, 22<<20)
		if err := r.ParseMultipartForm(12 << 20); err != nil {
			slog.Warn("send: multipart parse failed", "err", err)
			writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "bad multipart form"})
			return
		}
		if rejectIfTooManyFields(w, r) {
			return
		}
		key = r.FormValue("key")
		text = r.FormValue("text")
		node = r.FormValue("node")
		workspace = r.FormValue("workspace")
		resumeID = r.FormValue("resume_id")
		backend = r.FormValue("backend")
		accessProfile = r.FormValue("access_profile")
		fileIDs = r.MultipartForm.Value["file_ids"]

		files := r.MultipartForm.File["files"]
		if len(files) > 2 {
			writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "too many inline files (max 2); use /api/sessions/upload for more"})
			return
		}
		if len(files)+len(fileIDs) > maxFilesPerSend {
			writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": errTooManyFiles})
			return
		}
		for _, fh := range files {
			img, err := parseAttachmentFile(fh, false)
			if err != nil {
				writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
				return
			}
			images = append(images, img)
		}
	} else {
		r.Body = http.MaxBytesReader(w, r.Body, 2<<20) // 2 MB — leaves headroom over the 1 MB text field cap
		var req struct {
			Key           string   `json:"key"`
			Text          string   `json:"text"`
			Node          string   `json:"node"`
			Workspace     string   `json:"workspace"`
			ResumeID      string   `json:"resume_id"`
			Backend       string   `json:"backend"`
			AccessProfile string   `json:"access_profile"`
			FileIDs       []string `json:"file_ids"`
		}
		if err := decodeJSONBody(r, &req); err != nil {
			slog.Debug("dashboard send: invalid JSON", "err", err)
			writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "invalid JSON"})
			return
		}
		key = req.Key
		text = req.Text
		node = req.Node
		workspace = req.Workspace
		resumeID = req.ResumeID
		backend = req.Backend
		accessProfile = req.AccessProfile
		fileIDs = req.FileIDs
	}

	if len(fileIDs) > maxFilesPerSend {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": errTooManyFiles})
		return
	}

	// Pre-uploaded file IDs are ownership-checked (cross-user theft). Never
	// echo a client-supplied fid in the error (SetEscapeHTML(false) would
	// render it unescaped). TakeAll is atomic: if any fid is missing / expired
	// / foreign-owned nothing is consumed, so a batch retry works.
	owner, ok := uploadOwnerOrFail(w, r, h.auth, h.trustedProxy)
	if !ok {
		return
	}

	// Pure-input validation (key + text cap) runs BEFORE TakeAll consumes the
	// pre-uploaded entries, so a 400 here leaves the batch intact for retry;
	// rejections after TakeAll go through writeSendError with filesConsumed
	// so the client drops its stale chips (#2014).
	if key == "" {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "key is required"})
		return
	}
	// Validate key at the HTTP boundary so the raw attacker-controlled string
	// (C1 / bidi / non-UTF-8) never reaches slog attrs before sessionSend's
	// own validation.
	if err := session.ValidateSessionKey(key); err != nil {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "invalid key"})
		return
	}
	// Same per-field text cap as the WS path (maxWSSendTextBytes): the body
	// MaxBytesReader alone would let one multi-MB text reach CoalesceMessages
	// and CLI stdin.
	if len(text) > maxWSSendTextBytes {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "text too long"})
		return
	}

	filesConsumed := len(fileIDs) > 0 // true ⇒ TakeAll below deletes the store entries
	if filesConsumed {
		taken, err := h.uploadStore.TakeAll(fileIDs, owner)
		if err != nil {
			slog.Debug("send: one or more file_ids not found or expired", "count", len(fileIDs))
			writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "file not found or expired"})
			return
		}
		images = append(images, taken...)
	}

	if text == "" && len(images) == 0 {
		writeSendError(w, http.StatusBadRequest, "text or files required", filesConsumed)
		return
	}

	// Remote-node sends don't carry attachments (the node has no way to
	// host the workspace file locally). Reject BEFORE persisting so we
	// don't leave files on disk that will never be read. The deeper
	// remote-node branch below repeats this check for defence in depth.
	if node != "" && node != "local" && len(images) > 0 {
		writeSendError(w, http.StatusBadRequest, "files not supported for remote nodes", filesConsumed)
		return
	}

	// Persist file_ref attachments (PDFs) here, not in sessionSend: this is
	// the last HTTP-layer point with owner + workspace + key in scope, a
	// persist failure must surface synchronously as 4xx/5xx, and the
	// remote-node branch below takes no attachments. rollback runs on EVERY
	// failure path below and is cleared once sessionSend accepts.
	var rollback func()
	if hasPersistableAttachment(images) {
		// Validate workspace against allowedRoot BEFORE writing anything —
		// `workspace` is attacker-influenced and sessionSend's own check runs
		// only after we would already have persisted bytes.
		// resolveAttachmentWorkspace falls back to the router's saved
		// workspace because the dashboard does not re-send it every message.
		validatedWS, err := resolveAttachmentWorkspace(h.hub, key, workspace)
		if err != nil {
			slog.Warn("attachment workspace validation failed",
				"key", session.SanitizeLogAttr(key), "err", err)
			writeSendError(w, http.StatusBadRequest, "invalid workspace", filesConsumed)
			return
		}
		resolved, rb, perr := persistFileRefs(validatedWS, images, key, owner)
		if perr != nil {
			writeSendError(w, perr.status, perr.msg, filesConsumed)
			return
		}
		images = resolved
		rollback = rb
	}
	// Named helper so every early-return path below deletes the just-written
	// files. Safe to call when rollback is nil.
	cleanup := func() {
		if rollback != nil {
			rollback()
		}
	}

	// Remote node proxy
	if node != "" && node != "local" {
		if len(images) > 0 {
			cleanup()
			writeSendError(w, http.StatusBadRequest, "files not supported for remote nodes", filesConsumed)
			return
		}
		// Syntactic workspace gate (same as WS handleRemoteSend): the remote
		// node's own EvalSymlinks check may pass any absolute path when its
		// defaultWorkspace is unconfigured.
		if err := validateRemoteWorkspace(workspace); err != nil {
			writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "invalid workspace"})
			return
		}
		// Refuse remote dispatch for a non-default access-profile session —
		// the env overlay is host-local and never crosses the wire (RFC
		// project-access-profile P1-a). h.hub may be nil in test harnesses.
		// selectNodeForBackend below is the single node + cap authority (one
		// GetNode; no TOCTOU between lookup and cap check).
		if h.hub != nil {
			if err := gateRemoteAccessProfile(h.hub.resolver, node, key); err != nil {
				cleanup()
				writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
				return
			}
		}
		nc, err := selectNodeForBackend(h.nodeAccess, node, backend)
		if err != nil {
			cleanup()
			// 400 across the board (TestHandleAPISend_UnknownNode pins this);
			// the message is one of the structured sentinels (ErrUnknownBackend
			// / ErrNodeNotConnected / ErrNodeMissingCap).
			writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
			return
		}
		if nc == nil {
			// Unreachable given the node gate above; kept to match
			// selectNodeForBackend's documented nil-return contract.
			return
		}
		capturedKey, capturedText, capturedWorkspace := key, text, workspace
		// TrackSend so Shutdown waits for the in-flight RPC before closing node
		// connections (else the goroutine could write to a closed nc.conn); a
		// late arrival during shutdown gets 503 instead of a goroutine.
		var release func()
		if h.hub != nil {
			r, shuttingDown := h.hub.TrackSend()
			if shuttingDown {
				writeJSONStatus(w, http.StatusServiceUnavailable, map[string]string{"error": "server shutting down"})
				return
			}
			release = r
		}
		go func() {
			if release != nil {
				defer release()
			}
			// Inherit hub.ctx so shutdown cancels in-flight remote sends, but cap
			// the RPC at 60s so a hung node cannot leak a goroutine + sendWG
			// slot for the process lifetime. The nil-hub fallback (tests) uses
			// a bounded timeout too.
			var ctx context.Context
			var cancel context.CancelFunc
			if h.hub != nil {
				ctx, cancel = context.WithTimeout(h.hub.ctx, 60*time.Second)
			} else {
				ctx, cancel = context.WithTimeout(context.Background(), 30*time.Second)
			}
			defer cancel()
			if err := nc.Send(ctx, capturedKey, capturedText, capturedWorkspace); err != nil {
				slog.Error("remote send",
					"node", osutil.SanitizeForLog(node, 128),
					"key", session.SanitizeLogAttr(capturedKey), "err", err)
				// No ack channel left on HTTP — notify the key's subscribers (F1).
				if h.hub != nil {
					h.hub.broadcastSendError(capturedKey, asyncErrorMessage(err))
				}
			} else {
				nc.RefreshSubscription(capturedKey)
			}
			if h.hub != nil {
				h.hub.BroadcastSessionsUpdate()
			}
		}()
		writeJSONStatus(w, http.StatusAccepted, map[string]string{"status": "accepted", "key": key})
		return
	}

	reset, status, err := h.hub.sessionSend(sendParams{
		Key: key, Text: text, Images: images,
		Workspace: workspace, ResumeID: resumeID, Backend: backend,
		AccessProfile: accessProfile,
	}, h.hub.httpSendErrorCallback(key))
	if err != nil {
		cleanup()
		// Forward only the localised label: the raw error may embed workspace
		// paths or internal session keys.
		slog.Warn("dashboard sessionSend rejected", "key", session.SanitizeLogAttr(key), "err", err)
		writeSendError(w, http.StatusForbidden, asyncErrorMessage(err), filesConsumed)
		return
	}
	// From this point on the attachments have entered the dispatch pipeline
	// and must remain on disk until the GC ages them out — clear rollback.
	rollback = nil
	if reset {
		writeJSON(w, map[string]string{"key": key, "status": "reset"})
		return
	}
	writeJSONStatus(w, http.StatusAccepted, map[string]string{"status": string(status), "key": key})
}

// handleBind eagerly persists the per-chat workspace override for a freshly
// created dashboard session, WITHOUT spawning a CLI turn. POST /api/sessions/bind.
// Binding at creation time means a reload or a second browser before the first
// send still spawns in the chosen cwd instead of the workspace root.
//
// Security parity with handleSend: same send rate limiter (so /bind is not a
// cheaper override-flood vector), session key validation, allowedRoot
// validation before persisting, and an empty chat-key prefix (":agent") is
// refused. Remote-node sessions are a no-op.
func (h *SendHandler) handleBind(w http.ResponseWriter, r *http.Request) {
	if h.sendLimiter != nil && !h.sendLimiter.AllowRequest(r) {
		writeJSONStatus(w, http.StatusTooManyRequests, map[string]string{"error": sendRateLimitedMsg})
		return
	}
	r.Body = http.MaxBytesReader(w, r.Body, 64<<10)
	var req struct {
		Key       string `json:"key"`
		Node      string `json:"node"`
		Workspace string `json:"workspace"`
	}
	if err := decodeJSONBody(r, &req); err != nil {
		slog.Debug("dashboard bind: invalid JSON", "err", err)
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "invalid JSON"})
		return
	}
	if err := session.ValidateSessionKey(req.Key); err != nil {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "invalid key"})
		return
	}
	// Remote sessions resolve their workspace on their own node — never write a
	// local-router override for them. Ack so the fire-and-forget client is happy.
	if req.Node != "" && req.Node != "local" {
		writeJSON(w, map[string]bool{"ok": true})
		return
	}
	if req.Workspace == "" {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "workspace required"})
		return
	}
	wsPath, err := validateWorkspace(req.Workspace, h.hub.allowedRoot)
	if err != nil {
		// Mirror handleSend: scrub the attacker-influenced path before logging
		// and never echo the resolved filesystem path back to the client.
		slog.Warn("bind: workspace validation failed", "err", err, "workspace", osutil.SanitizeForLog(req.Workspace, 200))
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "invalid workspace"})
		return
	}
	// Persist under the 3-segment chat-key prefix (strip the trailing
	// ":agentID"), matching the SetWorkspace contract used by handleSend. A
	// key whose only colon is at index 0 (":agent") would persist the empty
	// chat key — refuse it.
	idx := strings.LastIndexByte(req.Key, ':')
	if idx <= 0 {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "invalid key"})
		return
	}
	h.hub.router.SetWorkspace(req.Key[:idx], wsPath)
	writeJSON(w, map[string]bool{"ok": true})
}

// attachmentDirPrefix is the workspace-relative prefix every path served
// via /api/sessions/attachment must start with (attachment.Dir in wire form).
// Kept separate from attachment.Dir so the HTTP guard cannot loosen silently.
//
// Wire contract (#468): forward slash on every platform, trailing `/`
// REQUIRED. Never substitute filepath.Separator or make it
// platform-conditional — every EventEntry.ImagePaths value uses `/`, and a
// mismatch with the HasPrefix gate either rejects legitimate paths or admits
// non-attachment ones. Downstream Joins convert via filepath.FromSlash.
const attachmentDirPrefix = ".naozhi/attachments/"

// maxAttachmentBytes caps the per-response size; oversize files are refused
// and the client falls back to the thumbnail. Stays below serveRaw's project
// file cap.
const maxAttachmentBytes = 16 << 20

// cleanAttachmentRelPath validates the workspace-relative attachment path
// the dashboard sends in ?path=. Returns (cleaned, "") on accept and
// ("", errMsg) on reject; errMsg is the client-facing JSON error string.
// Separate from handleAttachment so the path.Clean / filepath.Clean
// divergence guard is unit-testable (#536).
func cleanAttachmentRelPath(relRaw string) (string, string) {
	if len(relRaw) > 1024 {
		return "", "path too long"
	}
	if strings.ContainsRune(relRaw, 0) {
		return "", "invalid path"
	}
	if strings.ContainsRune(relRaw, '\\') || filepath.IsAbs(relRaw) {
		return "", "invalid path"
	}
	// path.Clean (POSIX) matches the forward-slash wire shape (backslash +
	// IsAbs already rejected); EvalSymlinks + attachRootAbs HasPrefix in the
	// handler is the authoritative containment check.
	cleaned := path.Clean(relRaw)
	if cleaned == ".." || strings.HasPrefix(cleaned, "../") || strings.Contains(cleaned, "/../") {
		return "", "invalid path"
	}
	// Defence-in-depth on non-Linux: path.Clean and filepath.Clean must
	// agree on the forward-slash form; any divergence means the wire shape
	// is not stable across the path/filepath boundary (#536).
	if osCleaned := filepath.ToSlash(filepath.Clean(filepath.FromSlash(cleaned))); osCleaned != cleaned {
		return "", "invalid path"
	}
	return cleaned, ""
}

// handleAttachment streams an on-disk inline image from the session
// workspace attachment directory for the dashboard lightbox "view original"
// (the data-URI thumbnail in EventEntry.Images remains the fallback).
//
// Request: GET /api/sessions/attachment?key=<session>&path=<ws-rel>
// Response: image/jpeg | image/png | image/gif | image/webp
//
// Authorization is the "session exists" boundary shared with
// /api/sessions/events. The path is pinned to attachmentDirPrefix under the
// session's workspace so a crafted key cannot exfiltrate other files.
func (h *SendHandler) handleAttachment(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query()
	key := q.Get("key")
	relRaw := q.Get("path")
	if key == "" || relRaw == "" {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "key and path are required"})
		return
	}
	if err := session.ValidateSessionKey(key); err != nil {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "invalid key"})
		return
	}

	// Strict path shape: workspace-relative, forward slashes only, no
	// absolute paths, no traversal, no NUL (mirrors resolveProjectFile).
	cleaned, errMsg := cleanAttachmentRelPath(relRaw)
	if errMsg != "" {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": errMsg})
		return
	}
	// Pin to the attachment subtree: persistFileRefs is the only producer
	// of these paths, so a legitimate URL always starts with the prefix.
	if !strings.HasPrefix(cleaned, attachmentDirPrefix) {
		writeJSONStatus(w, http.StatusNotFound, map[string]string{"error": "file not found"})
		return
	}

	// Resolve the workspace from the key only (live session, else router
	// fallback, as in resolveAttachmentWorkspace). A `workspace` query
	// parameter is deliberately NOT accepted.
	var ws string
	if sess := h.router.SessionFor(key); sess != nil {
		ws = sess.Workspace()
	}
	if ws == "" {
		chatKey := key
		if idx := strings.LastIndexByte(key, ':'); idx > 0 {
			chatKey = key[:idx]
		}
		ws = h.router.Workspace(chatKey)
	}
	if ws == "" {
		writeJSONStatus(w, http.StatusNotFound, map[string]string{"error": "file not found"})
		return
	}
	validatedWS, err := validateWorkspace(ws, h.hub.allowedRoot)
	if err != nil {
		writeJSONStatus(w, http.StatusNotFound, map[string]string{"error": "file not found"})
		return
	}

	abs := filepath.Join(validatedWS, filepath.FromSlash(cleaned))
	resolved, err := filepath.EvalSymlinks(abs)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			writeJSONStatus(w, http.StatusNotFound, map[string]string{"error": "file not found"})
			return
		}
		slog.Debug("attachment: eval symlinks failed", "err", err)
		writeJSONStatus(w, http.StatusNotFound, map[string]string{"error": "file not found"})
		return
	}
	// Symlink-escape defence: resolved MUST still live under validatedWS/attachmentDir.
	attachRootAbs := filepath.Join(validatedWS, filepath.FromSlash(strings.TrimSuffix(attachmentDirPrefix, "/")))
	if resolved != attachRootAbs &&
		!strings.HasPrefix(resolved, attachRootAbs+string(filepath.Separator)) {
		writeJSONStatus(w, http.StatusNotFound, map[string]string{"error": "file not found"})
		return
	}

	// Lstat (not Stat): a file swapped for a symlink after EvalSymlinks must
	// be rejected, not followed.
	info, err := os.Lstat(resolved)
	if err != nil || info.IsDir() {
		writeJSONStatus(w, http.StatusNotFound, map[string]string{"error": "file not found"})
		return
	}
	if info.Mode()&os.ModeSymlink != 0 {
		writeJSONStatus(w, http.StatusNotFound, map[string]string{"error": "file not found"})
		return
	}
	if info.Size() > maxAttachmentBytes {
		writeJSONStatus(w, http.StatusRequestEntityTooLarge, map[string]string{"error": "file too large"})
		return
	}

	// O_NOFOLLOW open (dashproject.OpenWorkspaceFile) closes the Lstat→Open
	// symlink-swap TOCTOU: a final-component symlink fails atomically with
	// ELOOP (#917).
	f, err := dashproject.OpenWorkspaceFile(resolved)
	if err != nil {
		// Symlink trap → same 404 as missing: escape attempts and absent
		// files must look identical.
		if errors.Is(err, syscall.ELOOP) {
			writeJSONStatus(w, http.StatusNotFound, map[string]string{"error": "file not found"})
			return
		}
		writeJSONStatus(w, http.StatusInternalServerError, map[string]string{"error": "open failed"})
		return
	}
	defer f.Close()

	// MIME is pinned from the extension: attachment.sanitizeExt is the only
	// producer of these files.
	ext := strings.ToLower(filepath.Ext(resolved))
	var mime string
	switch ext {
	case ".jpg", ".jpeg":
		mime = "image/jpeg"
	case ".png":
		mime = "image/png"
	case ".gif":
		mime = "image/gif"
	case ".webp":
		mime = "image/webp"
	default:
		// Unknown extension inside our own subtree — refuse rather than guess.
		writeJSONStatus(w, http.StatusNotFound, map[string]string{"error": "file not found"})
		return
	}

	// Defence-in-depth magic-byte check: if the sniffed MIME disagrees with
	// the extension pin, degrade to application/octet-stream +
	// Content-Disposition: attachment so a non-image that lands in our
	// subtree (e.g. a crafted SVG) can never render inline.
	disposition := "inline"
	disableInlineRender := false
	var sniffBuf [512]byte
	if n, _ := io.ReadFull(f, sniffBuf[:]); n > 0 {
		sniffed := http.DetectContentType(sniffBuf[:n])
		// SVG / XHTML / XML MUST never go inline even when sniff matches the
		// ext MIME (a future ext-allowlist relaxation must not enable
		// `<svg onload>`). Prefix match: DetectContentType may append
		// `; charset=...`.
		isXMLLike := strings.HasPrefix(sniffed, "image/svg+xml") ||
			strings.HasPrefix(sniffed, "application/xhtml+xml") ||
			strings.HasPrefix(sniffed, "text/xml") ||
			strings.HasPrefix(sniffed, "application/xml")
		if isXMLLike {
			slog.Warn("attachment: SVG/XML-like content detected, forcing attachment download",
				"ext", ext, "ext_mime", mime, "sniffed", sniffed,
				"path", filepath.Base(resolved))
			mime = "application/octet-stream"
			disposition = "attachment"
			disableInlineRender = true
		} else if !strings.EqualFold(sniffed, mime) {
			slog.Warn("attachment: magic-byte mismatch, degrading to octet-stream",
				"ext", ext, "ext_mime", mime, "sniffed", sniffed,
				"path", filepath.Base(resolved))
			mime = "application/octet-stream"
			disposition = "attachment"
			disableInlineRender = true
		}
	}
	// Rewind so http.ServeContent below streams the full payload, not just
	// the bytes after the sniff cursor.
	if _, err := f.Seek(0, io.SeekStart); err != nil {
		writeJSONStatus(w, http.StatusInternalServerError, map[string]string{"error": "seek failed"})
		return
	}

	// ETag = truncated sha256(size|mtime|salt): a plain "<size>-<mtime>" form
	// would leak exact size and mtime to any authenticated GET. Built via
	// strconv.AppendInt into a stack buffer — this runs on every attachment
	// GET.
	var etagBuf [48]byte
	etagSeed := buildAttachmentETagSeed(etagBuf[:0], info.Size(), info.ModTime())
	etagSum := sha256.Sum256(etagSeed)
	// 12 bytes (96-bit): a 64-bit truncation would put birthday-bound ETag
	// forgery within ~2^32 observed ETags.
	etag := `"` + hex.EncodeToString(etagSum[:12]) + `"`
	if inm := r.Header.Get("If-None-Match"); inm != "" && inm == etag {
		w.Header().Set("ETag", etag)
		w.WriteHeader(http.StatusNotModified)
		return
	}
	w.Header().Set("ETag", etag)
	w.Header().Set("Content-Type", mime)
	w.Header().Set("Content-Disposition", disposition)
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set("Cross-Origin-Resource-Policy", "same-origin")
	w.Header().Set("Cache-Control", "private, max-age=3600")
	if disableInlineRender {
		// Belt-and-braces: when degraded, blank out frame embedding so the
		// browser cannot side-load the byte stream into a context that
		// ignores Content-Disposition (e.g. <img>, <iframe>).
		w.Header().Set("X-Frame-Options", "DENY")
	}
	// Tight CSP: attachments are image-only, no inline scripts, no third-
	// party resources. sandbox closes top-level-navigation XSS channels for
	// formats (e.g. a future .svg) that slip past the ext check.
	w.Header().Set("Content-Security-Policy", "default-src 'none'; sandbox; img-src 'self' data:")

	http.ServeContent(w, r, filepath.Base(resolved), info.ModTime(), f)
}

// buildAttachmentETagSeed builds the SHA-256 input for the attachment ETag:
// "<size>|<mtime-millis>|<process-salt>" appended into dst (caller passes a
// stack buffer so the hot path stays allocation-free). Millisecond mtime, not
// nanos, denies an attacker ~30 bits of entropy to brute-force via
// If-None-Match probes; dashproject.FileETagSalt (per-process secret) defeats
// offline pre-imaging of (size, mtime). ETags rotate once per deploy.
func buildAttachmentETagSeed(dst []byte, size int64, mtime time.Time) []byte {
	dst = strconv.AppendInt(dst, size, 10)
	dst = append(dst, '|')
	dst = strconv.AppendInt(dst, mtime.UnixMilli(), 10)
	dst = append(dst, '|')
	dst = append(dst, dashproject.FileETagSalt...)
	return dst
}
