package server

import (
	"crypto/sha256"
	"crypto/subtle"
	"encoding/hex"
	"errors"
	"log/slog"
	"net/http"
	"strings"

	"github.com/naozhi/naozhi/internal/dashboard/auth"
)

// uploadOwner derives a stable owner key from the auth cookie, Bearer token,
// or (no-token mode) a per-browser nz_anon cookie, so co-NAT User B cannot
// claim User A's upload via TakeAll. ok=false means no per-browser key could
// be derived (every credential absent AND mintAnonCookie failed); callers
// MUST respond 503 rather than fall back to an IP-derived bucket (#501).
func uploadOwner(w http.ResponseWriter, r *http.Request, ah *auth.Handlers, trustedProxy bool) (string, bool) {
	// Honour the auth cookie only when it matches the current cookieMAC
	// (constant-time): a Bearer caller with a forged nz_auth cookie must not
	// bucket-shift onto another owner key. nil auth or empty MAC (no-token
	// mode) skips the branch — fail closed (#1399).
	if c, err := r.Cookie(auth.AuthCookieName); err == nil && c.Value != "" && ah != nil {
		if mac := ah.CookieMAC(); mac != "" &&
			subtle.ConstantTimeCompare([]byte(c.Value), []byte(mac)) == 1 {
			return ownerKeyFromCookie(c.Value), true
		}
	}
	if bearer := r.Header.Get("Authorization"); strings.HasPrefix(bearer, "Bearer ") {
		if token := strings.TrimPrefix(bearer, "Bearer "); token != "" {
			// 128-bit, matching ownerKeyFromCookie.
			sum := sha256.Sum256([]byte(token))
			return hex.EncodeToString(sum[:16]), true
		}
	}
	// Trust the cookie only in mintAnonCookie's wire shape; anything else
	// re-mints so the bucket is always rooted in server-generated bytes
	// (#485). connAdmission.deriveUploadOwner applies the same gate.
	if c, err := r.Cookie(anonCookieName); err == nil && isValidAnonCookieValue(c.Value) {
		return renewedOwnerFromCookie(w, r, ah, c.Value), true
	}
	if w != nil {
		val, err := mintAnonCookie(w, r, ah)
		if err == nil {
			return ownerKeyFromCookie(val), true
		}
		slog.Warn("uploadOwner: mintAnonCookie failed; refusing to fall back to IP-derived owner key", "err", err)
	}
	// No clientIP fallback: co-NAT browsers would share a bucket, reopening
	// the TakeAll cross-tenant window (#501).
	return "", false
}

// uploadOwnerOrFail wraps uploadOwner with the standard 503 response so
// individual handlers don't repeat the writeJSONStatus boilerplate. Returns
// owner + ok=true when a real per-browser key was minted/recovered; on
// ok=false the caller MUST stop processing — the response has already been
// written.
func uploadOwnerOrFail(w http.ResponseWriter, r *http.Request, ah *auth.Handlers, trustedProxy bool) (string, bool) {
	owner, ok := uploadOwner(w, r, ah, trustedProxy)
	if !ok {
		// 30s Retry-After mirrors the rate-limiter convention.
		w.Header().Set("Retry-After", "30")
		writeJSONStatus(w, http.StatusServiceUnavailable, map[string]string{"error": "could not derive upload owner; please retry"})
	}
	return owner, ok
}

// handleUpload accepts a single image OR PDF file and stores it for later
// reference by file_ids. PDFs are held in memory until the matching send
// call, at which point they are persisted into the session workspace so
// Claude can read them via its native Read tool (images remain inline).
// POST /api/sessions/upload  (multipart/form-data, field "file")
// Response: {"id": "<hex>", "kind": "image_inline"|"file_ref", "size": <bytes>, "name": "..."}
func (h *SendHandler) handleUpload(w http.ResponseWriter, r *http.Request) {
	if h.uploadLimiter != nil && !h.uploadLimiter.AllowRequest(r) {
		writeJSONStatus(w, http.StatusTooManyRequests, map[string]string{"error": "upload rate limit exceeded"})
		return
	}
	// PDF cap dominates the body size. MaxBytesReader gives a clean 413
	// rather than the opaque "bad multipart form" that ParseMultipartForm
	// returns when the body exceeds its own limit.
	r.Body = http.MaxBytesReader(w, r.Body, int64(uploadBodyBytes))
	if err := r.ParseMultipartForm(int64(uploadBodyBytes)); err != nil {
		// Don't echo stdlib internals (boundary details, file-system paths)
		// back to the client; log internally for operator triage.
		slog.Warn("upload: multipart parse failed", "err", err)
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "bad multipart form"})
		return
	}
	if rejectIfTooManyFields(w, r) {
		return
	}
	files := r.MultipartForm.File["file"]
	if len(files) != 1 {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": "exactly one file required"})
		return
	}
	att, err := parseAttachmentFile(files[0], true)
	if err != nil {
		writeJSONStatus(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}
	owner, ok := uploadOwnerOrFail(w, r, h.auth, h.trustedProxy)
	if !ok {
		return
	}
	id, err := h.uploadStore.Put(owner, att)
	if err != nil {
		// Distinguish per-owner quota from global exhaustion so the client
		// can show "你上传的文件过多" vs a generic "服务繁忙" prompt.
		msg := "too many pending uploads"
		if errors.Is(err, errUploadPerOwner) {
			msg = "upload quota exceeded for this user"
		}
		writeJSONStatus(w, http.StatusTooManyRequests, map[string]string{"error": msg})
		return
	}
	// Echo kind + size + name so the frontend can render a PDF chip vs an
	// image thumbnail without a second round-trip.
	writeJSON(w, map[string]any{
		"id":   id,
		"kind": att.Kind,
		"size": att.Size,
		"name": att.OrigName,
		"mime": att.MimeType,
	})
}
