package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The comment budget of the repository. Each counts comments breaking one of
// CLAUDE.md's Code Comments rules and may only go down: a count above its
// baseline fails, and so does one below it, so the change that fixes a
// comment lowers the baseline. Raising one needs an approved ledger entry
// (scripts/ratchet-raises.jsonl).
const (
	inFuncBlocksOver5Baseline = 30
	docOver10Baseline         = 38
	packageDocOver60Baseline  = 1
	reviewAnchorsBaseline     = 0
	historyPhrasesBaseline    = 40
	duplicateCommentsBaseline = 0
)

// budgetFloor: a repository this size has far more issue references than
// this; a walk that finds fewer has gone blind.
const budgetFloor = 500

func TestBudget(t *testing.T) {
	t.Parallel()
	c, err := count(filepath.Join("..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	for _, p := range budgetProblems(c) {
		t.Error(p)
	}
}

// budgetProblems reports a blind walk and every counter out of step with its
// baseline, in either direction.
func budgetProblems(c Counts) []string {
	if c.IssueRefs < budgetFloor {
		return []string{fmt.Sprintf("found %d issue references, below the floor of %d: the walk has gone blind", c.IssueRefs, budgetFloor)}
	}
	var out []string
	for _, r := range []struct {
		name          string
		got, baseline int
	}{
		{"InFuncBlocksOver5", c.InFuncBlocksOver5, inFuncBlocksOver5Baseline},
		{"DocOver10", c.DocOver10, docOver10Baseline},
		{"PackageDocOver60", c.PackageDocOver60, packageDocOver60Baseline},
		{"ReviewAnchors", c.ReviewAnchors, reviewAnchorsBaseline},
		{"HistoryPhrases", c.HistoryPhrases, historyPhrasesBaseline},
		{"DuplicateComments", c.DuplicateComments, duplicateCommentsBaseline},
	} {
		switch {
		case r.got > r.baseline:
			out = append(out, fmt.Sprintf("%s grew: %d > baseline %d. See CLAUDE.md § Code Comments; `go run ./tools/comment-budget -list %s` lists them:\n  %s",
				r.name, r.got, r.baseline, r.name, strings.Join(c.Offenders[r.name], "\n  ")))
		case r.got < r.baseline:
			out = append(out, fmt.Sprintf("%s dropped to %d (baseline %d): lower the baseline to %d", r.name, r.got, r.baseline, r.got))
		}
	}
	return out
}

func TestBudgetProblems_BothDirections(t *testing.T) {
	t.Parallel()
	at := Counts{InFuncBlocksOver5: inFuncBlocksOver5Baseline, DocOver10: docOver10Baseline,
		PackageDocOver60: packageDocOver60Baseline, ReviewAnchors: reviewAnchorsBaseline,
		HistoryPhrases: historyPhrasesBaseline, DuplicateComments: duplicateCommentsBaseline, IssueRefs: budgetFloor}
	if got := budgetProblems(at); len(got) != 0 {
		t.Fatalf("at baseline: %q", got)
	}
	grew := at
	grew.HistoryPhrases++
	if got := budgetProblems(grew); len(got) != 1 || !strings.Contains(got[0], "HistoryPhrases grew") {
		t.Errorf("growth: %q", got)
	}
	dropped := at
	dropped.DocOver10--
	if got := budgetProblems(dropped); len(got) != 1 || !strings.Contains(got[0], "lower the baseline") {
		t.Errorf("drop: %q", got)
	}
	blind := at
	blind.IssueRefs = 0
	if got := budgetProblems(blind); len(got) != 1 || !strings.Contains(got[0], "gone blind") {
		t.Errorf("blind: %q", got)
	}
}

func TestCountFile(t *testing.T) {
	t.Parallel()
	lines := func(n int, prefix string) string {
		var b strings.Builder
		for i := 0; i < n; i++ {
			b.WriteString(prefix + "// line\n")
		}
		return b.String()
	}
	src := "// Package p is a fixture.\npackage p\n\n" +
		lines(11, "") + // an 11-line godoc
		"func f() {\n" +
		lines(6, "\t") + // a 6-line block in a body
		"\tx := 1\n" +
		lines(5, "\t") + // a 5-line block: within the limit
		"\t_ = x\n" +
		"\t// see R244-SEC-P3-1 and #1234, #56\n" +
		"\t// this used to be a map; the flag was removed\n" +
		"\t//go:noinline is a directive, not prose (#999)\n" +
		"}\n\n" +
		"// g's doc: short, and the helper previously reserved stays legal.\n" +
		"func g() {}\n\n" +
		"// h is annotated twice.\n\n// h is annotated twice.\nfunc h() {}\n\n" + // an exact duplicate: counts once
		"// i has one note.\n\n// i has a different note.\nfunc i() {}\n\n" + // different text: not a duplicate
		"// j is noted once.\nvar sep = 1\n\n// j is noted once.\nfunc j() {}\n" // same text but split by code: not adjacent
	var c Counts
	c.Offenders = map[string][]string{}
	if err := countFile(&c, "p.go", []byte(src)); err != nil {
		t.Fatal(err)
	}
	want := Counts{InFuncBlocksOver5: 1, DocOver10: 1, ReviewAnchors: 1, HistoryPhrases: 2, DuplicateComments: 1, IssueRefs: 1}
	if c.InFuncBlocksOver5 != want.InFuncBlocksOver5 || c.DocOver10 != want.DocOver10 ||
		c.ReviewAnchors != want.ReviewAnchors || c.HistoryPhrases != want.HistoryPhrases ||
		c.DuplicateComments != want.DuplicateComments || c.IssueRefs != want.IssueRefs {
		t.Errorf("counts = %+v, want %+v", c, want)
	}
	gen := "// Code generated by x; DO NOT EDIT.\n\npackage p\n\n" + lines(20, "") + "func f() {}\n"
	var g Counts
	g.Offenders = map[string][]string{}
	if err := countFile(&g, "gen.go", []byte(gen)); err != nil {
		t.Fatal(err)
	}
	if g.DocOver10 != 0 {
		t.Errorf("a generated file was counted: %+v", g)
	}
}

// TestCount_Walk: the walk counts non-test Go files under a root named naozhi
// (CI's checkout, the owner's worktree) and skips the old clone nested in it,
// agent worktrees and other nested checkouts, test files, testdata and
// vendored trees.
func TestCount_Walk(t *testing.T) {
	t.Parallel()
	root := filepath.Join(t.TempDir(), "naozhi")
	src := "package p\n\n// f was removed once.\nfunc f() {}\n"
	for _, p := range []string{
		"internal/a/a.go",
		"cmd/naozhi/main.go",
		"naozhi/internal/a/a.go",
		"internal/a/a_test.go",
		"internal/a/testdata/x.go",
		"test/e2e/node_modules/x/x.go",
		".claude/worktrees/agent-x/internal/a/a.go",
		"wt/.git",
		"wt/internal/a/a.go",
	} {
		full := filepath.Join(root, p)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(src), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	c, err := count(root)
	if err != nil {
		t.Fatal(err)
	}
	if c.HistoryPhrases != 2 {
		t.Errorf("HistoryPhrases = %d, want 2 (internal/a/a.go and cmd/naozhi/main.go only): %v", c.HistoryPhrases, c.Offenders["HistoryPhrases"])
	}
}
