package main

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/naozhi/naozhi/internal/osutil"
)

const (
	setupBaseURL      = "https://ilinkai.weixin.qq.com"
	setupPollInterval = 2 * time.Second
	setupPollTimeout  = 5 * time.Minute
)

// setupHTTPClient is a dedicated client for the interactive setup flow so we
// don't inherit http.DefaultClient's no-timeout / 10-redirect behavior. Any
// HTTPS redirect from the vendor API is returned unfollowed (ErrUseLastResponse)
// so a compromised DNS or misconfigured endpoint can't pivot us to a different
// host while we're sending a QR-code identifier.
var setupHTTPClient = &http.Client{
	Timeout: 15 * time.Second,
	CheckRedirect: func(_ *http.Request, _ []*http.Request) error {
		return http.ErrUseLastResponse
	},
	Transport: &http.Transport{
		TLSClientConfig: &tls.Config{MinVersion: tls.VersionTLS12},
	},
}

// defaultConfigTemplate is intentionally minimal: only the fields a fresh
// user cannot infer are emitted. Everything else (server.addr, session.ttl,
// session.max_procs, session.queue.*, session.watchdog.*, log.level,
// workspace.*, shim.*) is populated at runtime by config.applyDefaults, so
// listing them here only creates a second source of truth that drifts.
//
// The template prints the following keys:
//   - cli.path / cli.model — users routinely override these for custom CLI
//     locations or alternate models; emitting them gives them an obvious
//     anchor to edit.
//   - platforms.weixin.token — the one datum `naozhi setup weixin` actually
//     produces, and the reason this template exists.
//
// For every other option, see config.example.yaml in the repo.
//
// R172-SEC-M3: the token is NOT interpolated here. setupWriteConfig parses
// this template as YAML and writes the token through updateWeixinToken's
// yaml.Node + DoubleQuotedStyle path so a vendor-API token containing
// YAML specials (':', '#', '\n', '"') is always emitted as a properly
// escaped scalar. A compromised WeChat QR endpoint (MITM) therefore
// cannot smuggle `token: "valid"\nadmin: true` or similar into the
// generated config.
var defaultConfigTemplate = `# naozhi config — generated by 'naozhi setup weixin'.
# Other defaults (server.addr, session.ttl, log.level, etc.) are applied at
# runtime; see config.example.yaml for the full reference of available keys.

cli:
  path: "claude"
  model: "sonnet"

platforms:
  weixin:
    token: ""
`

func runSetup(args []string) {
	if len(args) == 0 {
		fmt.Println("Usage: naozhi setup <platform>")
		fmt.Println()
		fmt.Println("Platforms:")
		fmt.Println("  weixin    WeChat (iLink Bot)")
		os.Exit(1)
	}

	switch args[0] {
	case "weixin":
		runSetupWeixin(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "unknown platform: %s\n", args[0])
		os.Exit(1)
	}
}

func runSetupWeixin(args []string) {
	fs := flag.NewFlagSet("setup weixin", flag.ExitOnError)
	configPath := fs.String("config", "", "config file path (default ~/.naozhi/config.yaml)")
	fs.Parse(args)

	if *configPath == "" {
		home, _ := os.UserHomeDir()
		*configPath = filepath.Join(home, ".naozhi", "config.yaml")
	}

	// Check claude CLI
	if _, err := exec.LookPath("claude"); err != nil {
		fmt.Println("Warning: claude CLI not found in PATH")
		fmt.Println("Install: https://claude.ai/code")
		fmt.Println()
	}

	ctx, cancel := context.WithTimeout(context.Background(), setupPollTimeout)
	defer cancel()

	// Step 1: Get QR code
	fmt.Println("Fetching WeChat login QR code...")
	qr, err := setupGetQRCode(ctx)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to get QR code: %v\n", err)
		os.Exit(1)
	}

	fmt.Println()
	fmt.Println("Scan with WeChat (use the bot account):")
	fmt.Printf("\n  %s\n\n", qr.QRCodeImgContent)
	fmt.Println("Waiting for confirmation...")

	// Step 2: Poll for status
	token, err := setupPollStatus(ctx, qr.QRCode)
	if err != nil {
		fmt.Fprintf(os.Stderr, "\nLogin failed: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("\nLogin successful!")

	// Step 3: Write config
	if err := setupWriteConfig(*configPath, token); err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write config: %v\n", err)
		fmt.Println()
		fmt.Println("Add manually to config.yaml:")
		fmt.Println("  platforms:")
		fmt.Println("    weixin:")
		fmt.Printf("      token: \"%s\"\n", token)
		os.Exit(1)
	}

	fmt.Printf("\nConfig saved: %s\n", *configPath)
	fmt.Println()
	fmt.Printf("Start: naozhi --config %s\n", *configPath)
}

// --- QR Code API ---

type setupQRResp struct {
	Ret              int    `json:"ret"`
	QRCode           string `json:"qrcode"`
	QRCodeImgContent string `json:"qrcode_img_content"`
}

type setupStatusResp struct {
	Status     string `json:"status"` // "wait" | "scaned" | "confirmed" | "expired"
	BotToken   string `json:"bot_token,omitempty"`
	ILinkBotID string `json:"ilink_bot_id,omitempty"`
}

func setupGetQRCode(ctx context.Context) (*setupQRResp, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		setupBaseURL+"/ilink/bot/get_bot_qrcode?bot_type=3", nil)
	if err != nil {
		return nil, err
	}
	resp, err := setupHTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("QR code API returned HTTP %d", resp.StatusCode)
	}

	data, err := io.ReadAll(io.LimitReader(resp.Body, 64*1024))
	if err != nil {
		return nil, err
	}
	var qr setupQRResp
	if err := json.Unmarshal(data, &qr); err != nil {
		return nil, err
	}
	if qr.Ret != 0 {
		return nil, fmt.Errorf("API error: ret=%d, body=%s", qr.Ret, string(data))
	}
	if qr.QRCode == "" || qr.QRCodeImgContent == "" {
		return nil, fmt.Errorf("empty QR code in response")
	}
	return &qr, nil
}

func setupPollStatus(ctx context.Context, qrcode string) (string, error) {
	ticker := time.NewTicker(setupPollInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return "", fmt.Errorf("timed out waiting for scan")
		case <-ticker.C:
			status, err := setupCheckStatus(ctx, qrcode)
			if err != nil {
				return "", err
			}
			switch status.Status {
			case "confirmed":
				if status.BotToken == "" {
					return "", fmt.Errorf("confirmed but no token returned")
				}
				return status.BotToken, nil
			case "expired":
				return "", fmt.Errorf("QR code expired, please retry")
			case "scaned":
				fmt.Print(".")
			}
		}
	}
}

func setupCheckStatus(ctx context.Context, qrcode string) (*setupStatusResp, error) {
	u := setupBaseURL + "/ilink/bot/get_qrcode_status?qrcode=" + url.QueryEscape(qrcode)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("iLink-App-ClientVersion", "1")

	resp, err := setupHTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("status check API returned HTTP %d", resp.StatusCode)
	}

	data, err := io.ReadAll(io.LimitReader(resp.Body, 64*1024))
	if err != nil {
		return nil, err
	}
	var s setupStatusResp
	if err := json.Unmarshal(data, &s); err != nil {
		return nil, err
	}
	return &s, nil
}

// --- Config writing ---

func setupWriteConfig(path, token string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return err
	}

	// R172-SEC-M3: both new and existing files route the token through
	// updateWeixinToken so yaml.Node + DoubleQuotedStyle escapes any
	// YAML specials (including `"`, `#`, `:`, newline, C0 controls)
	// uniformly. The old fast path `fmt.Sprintf(template, token)` trusted
	// the vendor QR API to never emit `"\nadmin: true` — a single stray
	// double-quote or newline in a MITM'd response would have split the
	// YAML document or injected unrelated keys.
	var base []byte
	if _, err := os.Stat(path); errors.Is(err, fs.ErrNotExist) {
		base = []byte(defaultConfigTemplate)
	} else {
		base, err = os.ReadFile(path)
		if err != nil {
			return err
		}
	}
	updated, err := updateWeixinToken(base, token)
	if err != nil {
		return err
	}
	return osutil.WriteFileAtomic(path, updated, 0600)
}

func updateWeixinToken(data []byte, token string) ([]byte, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, err
	}
	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return nil, fmt.Errorf("invalid YAML document")
	}

	root := doc.Content[0]
	platforms := yamlFindOrCreateMap(root, "platforms")
	weixin := yamlFindOrCreateMap(platforms, "weixin")
	yamlSetScalar(weixin, "token", token)

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&doc); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// yamlFindOrCreateMap finds a mapping child by key, or creates one.
func yamlFindOrCreateMap(parent *yaml.Node, key string) *yaml.Node {
	if parent.Kind != yaml.MappingNode {
		return parent
	}
	for i := 0; i < len(parent.Content)-1; i += 2 {
		if parent.Content[i].Value == key {
			return parent.Content[i+1]
		}
	}
	keyNode := &yaml.Node{Kind: yaml.ScalarNode, Value: key}
	valNode := &yaml.Node{Kind: yaml.MappingNode}
	parent.Content = append(parent.Content, keyNode, valNode)
	return valNode
}

// yamlSetScalar sets or creates a scalar value in a mapping node.
func yamlSetScalar(parent *yaml.Node, key, value string) {
	if parent.Kind != yaml.MappingNode {
		return
	}
	for i := 0; i < len(parent.Content)-1; i += 2 {
		if parent.Content[i].Value == key {
			parent.Content[i+1].Value = value
			parent.Content[i+1].Tag = ""
			parent.Content[i+1].Style = yaml.DoubleQuotedStyle
			return
		}
	}
	keyNode := &yaml.Node{Kind: yaml.ScalarNode, Value: key}
	valNode := &yaml.Node{Kind: yaml.ScalarNode, Value: value, Style: yaml.DoubleQuotedStyle}
	parent.Content = append(parent.Content, keyNode, valNode)
}
