package main

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net/http"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"gopkg.in/yaml.v3"

	"github.com/naozhi/naozhi/internal/osutil"
)

const (
	setupBaseURL      = "https://ilinkai.weixin.qq.com"
	setupPollInterval = 2 * time.Second
	setupPollTimeout  = 5 * time.Minute
)

// setupHTTPClient has a timeout and never follows redirects so a compromised
// DNS or misconfigured endpoint cannot pivot the QR-code identifier to another host.
var setupHTTPClient = &http.Client{
	Timeout: 15 * time.Second,
	CheckRedirect: func(_ *http.Request, _ []*http.Request) error {
		return http.ErrUseLastResponse
	},
	Transport: &http.Transport{
		TLSClientConfig: &tls.Config{MinVersion: tls.VersionTLS12},
	},
}

// defaultConfigTemplate is intentionally minimal: everything else is populated
// by config.applyDefaults, and listing it here would drift. The token is NOT
// interpolated — setupWriteConfig routes it through updateWeixinConfig's
// yaml.Node DoubleQuotedStyle path so a MITM'd vendor token containing YAML
// specials cannot inject keys into the generated config. im_access is added
// the same way by ensureWeixinAccess.
var defaultConfigTemplate = `# naozhi config — generated by 'naozhi setup weixin'.
# Other defaults (server.addr, session.ttl, log.level, etc.) are applied at
# runtime; see config.example.yaml for the full reference of available keys.

cli:
  path: "claude"
  # model left empty on purpose: naozhi-spawned claude reads ~/.claude/settings.json
  # directly (--setting-sources user), so the model resolves the same way it does
  # for the TUI claude. Set a value here only to FORCE a model that overrides the
  # user's settings.json for naozhi sessions.
  model: ""

platforms:
  weixin:
    token: ""
`

func runSetup(args []string) {
	if len(args) == 0 {
		fmt.Println("Usage: naozhi setup <platform>")
		fmt.Println()
		fmt.Println("Platforms:")
		fmt.Println("  weixin    WeChat (iLink Bot)")
		os.Exit(1)
	}

	switch args[0] {
	case "weixin":
		runSetupWeixin(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "unknown platform: %s\n", args[0])
		os.Exit(1)
	}
}

func runSetupWeixin(args []string) {
	fs, configPath := newSubFlagSet("setup weixin", "")
	fs.Parse(args)

	if *configPath == "" {
		home, _ := os.UserHomeDir()
		*configPath = filepath.Join(home, ".naozhi", "config.yaml")
	}

	if _, err := exec.LookPath("claude"); err != nil {
		fmt.Println("Warning: claude CLI not found in PATH")
		fmt.Println("Install: https://claude.ai/code")
		fmt.Println()
	}

	ctx, cancel := context.WithTimeout(context.Background(), setupPollTimeout)
	defer cancel()

	// Step 1: Get QR code
	fmt.Println("Fetching WeChat login QR code...")
	qr, err := setupGetQRCode(ctx)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to get QR code: %v\n", err)
		os.Exit(1)
	}

	fmt.Println()
	fmt.Println("Scan with WeChat (use the bot account):")
	fmt.Printf("\n  %s\n\n", qr.QRCodeImgContent)
	fmt.Println("Waiting for confirmation...")

	// Step 2: Poll for status
	login, err := setupPollStatus(ctx, qr.QRCode)
	if err != nil {
		fmt.Fprintf(os.Stderr, "\nLogin failed: %v\n", err)
		os.Exit(1)
	}
	token := login.BotToken

	fmt.Println("\nLogin successful!")

	// Step 3: Write config
	access, err := setupWriteConfig(*configPath, token, login.ILinkUserID)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to write config: %v\n", err)
		fmt.Println()
		fmt.Println("Add manually to config.yaml:")
		printWeixinManualConfig(os.Stdout, token, login.ILinkUserID)
		os.Exit(1)
	}

	fmt.Printf("\nConfig saved: %s\n", *configPath)
	printWeixinAccess(os.Stdout, access, login.ILinkUserID)
	fmt.Println()
	fmt.Printf("Start: naozhi --config %s\n", *configPath)
}

// --- QR Code API ---

type setupQRResp struct {
	Ret              int    `json:"ret"`
	QRCode           string `json:"qrcode"`
	QRCodeImgContent string `json:"qrcode_img_content"`
}

type setupStatusResp struct {
	Status     string `json:"status"` // "wait" | "scaned" | "confirmed" | "expired"
	BotToken   string `json:"bot_token,omitempty"`
	ILinkBotID string `json:"ilink_bot_id,omitempty"`
	// ILinkUserID is the WeChat user who scanned the QR code (...@im.wechat),
	// the same ID space as an inbound message's from_user_id.
	ILinkUserID string `json:"ilink_user_id,omitempty"`
}

func setupGetQRCode(ctx context.Context) (*setupQRResp, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet,
		setupBaseURL+"/ilink/bot/get_bot_qrcode?bot_type=3", nil)
	if err != nil {
		return nil, err
	}
	resp, err := setupHTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("QR code API returned HTTP %d", resp.StatusCode)
	}

	data, err := io.ReadAll(io.LimitReader(resp.Body, 64*1024))
	if err != nil {
		return nil, err
	}
	var qr setupQRResp
	if err := json.Unmarshal(data, &qr); err != nil {
		return nil, err
	}
	if qr.Ret != 0 {
		// A MITM'd vendor body could carry ANSI escapes that hijack the terminal.
		return nil, fmt.Errorf("API error: ret=%d, body=%s", qr.Ret, osutil.SanitizeForLog(string(data), 256))
	}
	if qr.QRCode == "" || qr.QRCodeImgContent == "" {
		return nil, fmt.Errorf("empty QR code in response")
	}
	return &qr, nil
}

func setupPollStatus(ctx context.Context, qrcode string) (*setupStatusResp, error) {
	ticker := time.NewTicker(setupPollInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return nil, fmt.Errorf("timed out waiting for scan")
		case <-ticker.C:
			status, err := setupCheckStatus(ctx, qrcode)
			if err != nil {
				return nil, err
			}
			switch status.Status {
			case "confirmed":
				if status.BotToken == "" {
					return nil, fmt.Errorf("confirmed but no token returned")
				}
				return status, nil
			case "expired":
				return nil, fmt.Errorf("QR code expired, please retry")
			case "scaned":
				fmt.Print(".")
			}
		}
	}
}

func setupCheckStatus(ctx context.Context, qrcode string) (*setupStatusResp, error) {
	u := setupBaseURL + "/ilink/bot/get_qrcode_status?qrcode=" + url.QueryEscape(qrcode)
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, u, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("iLink-App-ClientVersion", "1")

	resp, err := setupHTTPClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("status check API returned HTTP %d", resp.StatusCode)
	}

	data, err := io.ReadAll(io.LimitReader(resp.Body, 64*1024))
	if err != nil {
		return nil, err
	}
	var s setupStatusResp
	if err := json.Unmarshal(data, &s); err != nil {
		return nil, err
	}
	return &s, nil
}

// --- Config writing ---

// setupWriteConfig writes the weixin token to path, creating the file from
// defaultConfigTemplate when absent, and reports what it did to im_access
// for the scanning user userID (see ensureWeixinAccess).
func setupWriteConfig(path, token, userID string) (weixinAccess, error) {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return weixinAccessUnset, err
	}

	// New and existing files both go through updateWeixinConfig so YAML
	// specials in a vendor token are always escaped, never interpolated.
	var base []byte
	fresh := false
	if _, err := os.Stat(path); errors.Is(err, fs.ErrNotExist) {
		base = []byte(defaultConfigTemplate)
		fresh = true
	} else {
		base, err = os.ReadFile(path)
		if err != nil {
			return weixinAccessUnset, err
		}
	}
	updated, access, err := updateWeixinConfig(base, token, userID, fresh)
	if err != nil {
		return weixinAccessUnset, err
	}
	return access, osutil.WriteFileAtomic(path, updated, 0600)
}

func updateWeixinConfig(data []byte, token, userID string, fresh bool) ([]byte, weixinAccess, error) {
	var doc yaml.Node
	if err := yaml.Unmarshal(data, &doc); err != nil {
		return nil, weixinAccessUnset, err
	}
	if doc.Kind != yaml.DocumentNode || len(doc.Content) == 0 {
		return nil, weixinAccessUnset, fmt.Errorf("invalid YAML document")
	}

	root := doc.Content[0]
	platforms := yamlFindOrCreateMap(root, "platforms")
	weixin := yamlFindOrCreateMap(platforms, "weixin")
	yamlSetScalar(weixin, "token", token)
	access := ensureWeixinAccess(root, userID, fresh)

	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(&doc); err != nil {
		return nil, weixinAccessUnset, err
	}
	if err := enc.Close(); err != nil {
		return nil, weixinAccessUnset, err
	}
	return buf.Bytes(), access, nil
}

// weixinAccess is what ensureWeixinAccess did to im_access.
type weixinAccess int

const (
	weixinAccessUnset       weixinAccess = iota // existing file, no usable ID: nothing written
	weixinAccessAllowed                         // added platforms.weixin.allowed_users: [scanning user]
	weixinAccessDefaultDeny                     // fresh file, no usable ID: added default_deny: true
	weixinAccessKept                            // platforms.weixin already existed; untouched
	weixinAccessKeptWithout                     // as Kept, but the entry does not list the scanning user
)

// ensureWeixinAccess restricts the weixin entry point to the user who scanned
// the login QR code. An existing im_access.platforms.weixin entry is never
// modified, and default_deny is written only to a fresh file: in an existing
// one it would lock out the other platforms.
func ensureWeixinAccess(root *yaml.Node, userID string, fresh bool) weixinAccess {
	id, idOK := setupAccessID(userID)
	if entry := yamlLookup(yamlLookup(yamlLookup(root, "im_access"), "platforms"), "weixin"); entry != nil {
		if idOK && !yamlListsID(entry, id) {
			return weixinAccessKeptWithout
		}
		return weixinAccessKept
	}
	if !idOK && !fresh {
		return weixinAccessUnset
	}
	imAccess := yamlFindOrCreateMap(root, "im_access")
	if imAccess.Kind != yaml.MappingNode {
		return weixinAccessUnset
	}
	if !idOK {
		imAccess.Content = append(imAccess.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "default_deny"},
			&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!bool", Value: "true"})
		return weixinAccessDefaultDeny
	}
	platforms := yamlFindOrCreateMap(imAccess, "platforms")
	if platforms.Kind != yaml.MappingNode {
		return weixinAccessUnset
	}
	weixin := yamlFindOrCreateMap(platforms, "weixin")
	weixin.Content = append(weixin.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "allowed_users"},
		&yaml.Node{Kind: yaml.SequenceNode, Style: yaml.FlowStyle, Content: []*yaml.Node{
			{Kind: yaml.ScalarNode, Value: id, Style: yaml.DoubleQuotedStyle},
		}})
	return weixinAccessAllowed
}

// setupAccessID returns the trimmed vendor-reported user ID when it is safe to
// write and print: at most 256 bytes of printable UTF-8 with no ${, a subset
// of what config.validateIMAccess accepts.
func setupAccessID(raw string) (string, bool) {
	id := strings.TrimSpace(raw)
	if id == "" || len(id) > 256 || !utf8.ValidString(id) || strings.Contains(id, "${") {
		return "", false
	}
	if strings.ContainsFunc(id, func(r rune) bool { return !unicode.IsPrint(r) }) {
		return "", false
	}
	return id, true
}

// printWeixinAccess tells the operator who may now use the weixin bot.
func printWeixinAccess(w io.Writer, access weixinAccess, userID string) {
	id, _ := setupAccessID(userID)
	switch access {
	case weixinAccessAllowed:
		fmt.Fprintf(w, "IM access: weixin only accepts messages from %s (im_access.platforms.weixin.allowed_users).\n", id)
		fmt.Fprintln(w, "To let another WeChat account in, add its ID there: a refused sender is told their ID, and the Info log line \"im access denied\" carries it as user.")
	case weixinAccessDefaultDeny:
		fmt.Fprintln(w, "IM access: the login did not report your WeChat user ID, so im_access.default_deny is on and every sender is refused.")
		fmt.Fprintln(w, "Message the bot once: the refusal reply (and the Info log line \"im access denied\", field user) carries the ID to add to im_access.platforms.weixin.allowed_users.")
	case weixinAccessKept:
		fmt.Fprintln(w, "IM access: kept the existing im_access.platforms.weixin entry.")
	case weixinAccessKeptWithout:
		fmt.Fprintf(w, "IM access: kept the existing im_access.platforms.weixin entry; it does not list the account that just logged in (%s). Add it to allowed_users if that account should use the bot.\n", id)
	default:
		fmt.Fprintln(w, "IM access: im_access not changed; unless im_access.default_deny is on, anyone can message the weixin bot. Restrict it with:")
		printWeixinAccessTemplate(w, id)
	}
}

// printWeixinManualConfig prints the config to paste when writing it failed.
// It always carries an im_access block, so the pasted bot is never open.
func printWeixinManualConfig(w io.Writer, token, userID string) {
	id, _ := setupAccessID(userID)
	fmt.Fprintln(w, "  platforms:")
	fmt.Fprintln(w, "    weixin:")
	fmt.Fprintf(w, "      token: \"%s\"\n", token)
	printWeixinAccessTemplate(w, id)
}

// printWeixinAccessTemplate prints an im_access block allowlisting id, or a
// placeholder plus how to learn the real ID when id is empty.
func printWeixinAccessTemplate(w io.Writer, id string) {
	shown := id
	if shown == "" {
		shown = "<your ID>"
	}
	fmt.Fprintln(w, "  im_access:")
	fmt.Fprintln(w, "    platforms:")
	fmt.Fprintln(w, "      weixin:")
	fmt.Fprintf(w, "        allowed_users: [%s]\n", strconv.Quote(shown))
	if id == "" {
		fmt.Fprintln(w, "A refused sender is told their ID, and the Info log line \"im access denied\" carries it as user: start with a placeholder ID to learn yours.")
	}
}

// yamlLookup returns the value under key in a mapping node, or nil.
func yamlLookup(parent *yaml.Node, key string) *yaml.Node {
	if parent == nil || parent.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i < len(parent.Content)-1; i += 2 {
		if parent.Content[i].Value == key {
			return parent.Content[i+1]
		}
	}
	return nil
}

// yamlListsID reports whether an im_access rule node lists id in
// allowed_users or admin_users.
func yamlListsID(rule *yaml.Node, id string) bool {
	for _, field := range []string{"allowed_users", "admin_users"} {
		list := yamlLookup(rule, field)
		if list == nil || list.Kind != yaml.SequenceNode {
			continue
		}
		for _, item := range list.Content {
			if strings.TrimSpace(item.Value) == id {
				return true
			}
		}
	}
	return false
}

// yamlFindOrCreateMap finds a mapping child by key, or creates one. An empty
// value (`key:` with nothing after it) becomes an empty mapping.
func yamlFindOrCreateMap(parent *yaml.Node, key string) *yaml.Node {
	if parent.Kind != yaml.MappingNode {
		return parent
	}
	for i := 0; i < len(parent.Content)-1; i += 2 {
		if parent.Content[i].Value == key {
			v := parent.Content[i+1]
			if v.Kind == yaml.ScalarNode && v.Tag == "!!null" {
				*v = yaml.Node{Kind: yaml.MappingNode}
			}
			return v
		}
	}
	keyNode := &yaml.Node{Kind: yaml.ScalarNode, Value: key}
	valNode := &yaml.Node{Kind: yaml.MappingNode}
	parent.Content = append(parent.Content, keyNode, valNode)
	return valNode
}

// yamlSetScalar sets or creates a scalar value in a mapping node.
func yamlSetScalar(parent *yaml.Node, key, value string) {
	if parent.Kind != yaml.MappingNode {
		return
	}
	for i := 0; i < len(parent.Content)-1; i += 2 {
		if parent.Content[i].Value == key {
			parent.Content[i+1].Value = value
			parent.Content[i+1].Tag = ""
			parent.Content[i+1].Style = yaml.DoubleQuotedStyle
			return
		}
	}
	keyNode := &yaml.Node{Kind: yaml.ScalarNode, Value: key}
	valNode := &yaml.Node{Kind: yaml.ScalarNode, Value: value, Style: yaml.DoubleQuotedStyle}
	parent.Content = append(parent.Content, keyNode, valNode)
}
