// Package contractjs builds internal/server/static/contract.js — the
// generated frontend contract (#2539): WS message types (from wsproto), the
// /api/* route table (from the routes.golden.json snapshot TestRoutesSnapshot
// keeps in sync with registration) and the json field names of the dashboard
// export structs. The dashboard reads NZ_CONTRACT instead of re-typing
// backend literals, so a struct-tag or route change breaks a Go test, not
// production (#2432/#2433/#2476 class).
//
// tools/gen-contract writes the file; contractjs's own test rebuilds it in
// memory and byte-compares against the committed file, so a stale
// contract.js fails CI.
package contractjs

import (
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"

	"github.com/naozhi/naozhi/internal/dashboard/project"
	dashsession "github.com/naozhi/naozhi/internal/dashboard/session"
	"github.com/naozhi/naozhi/internal/server"
	"github.com/naozhi/naozhi/internal/session"
	"github.com/naozhi/naozhi/internal/wsproto"
)

// Build renders contract.js. routesGoldenPath points at
// internal/server/testdata/routes.golden.json.
func Build(routesGoldenPath string) (string, error) {
	var b strings.Builder
	b.WriteString(`// Code generated by tools/gen-contract; DO NOT EDIT (#2539).
// Classic script, ES5-safe, one global, no top-level const/let (#1954).
// Node consumers (test/e2e/mock-server.js) require() the same file.
(function (root) {
  var NZ_CONTRACT = {
`)

	// WS: every browser message type, outbound and inbound.
	b.WriteString("    WS: {\n")
	types := make([]string, 0, len(wsproto.Frames))
	for typ := range wsproto.Frames {
		types = append(types, string(typ))
	}
	for _, typ := range []wsproto.MsgType{
		wsproto.TypeAuth, wsproto.TypeSubscribe, wsproto.TypeUnsubscribe,
		wsproto.TypeSend, wsproto.TypeInterrupt, wsproto.TypePing,
		wsproto.TypeAgentSubscribe, wsproto.TypeAgentUnsubscribe,
	} {
		types = append(types, string(typ))
	}
	sort.Strings(types)
	for _, typ := range types {
		fmt.Fprintf(&b, "      %s: '%s',\n", typ, typ)
	}
	b.WriteString("    },\n")

	// API: the /api/* route paths from the tested route snapshot.
	paths, err := apiPaths(routesGoldenPath)
	if err != nil {
		return "", err
	}
	b.WriteString("    API: {\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "      %s: '%s',\n", apiKey(p), p)
	}
	b.WriteString("    },\n")

	// F: json field names of the dashboard export structs.
	b.WriteString("    F: {\n")
	for _, sec := range []struct {
		name string
		v    any
	}{
		{"sessions", session.SessionSnapshot{}},
		{"stats", dashsession.ContractStats},
		{"projects", project.ContractProjectsEntry},
		{"health", server.ContractHealthAuth},
	} {
		fmt.Fprintf(&b, "      %s: {\n", sec.name)
		for _, f := range jsonFields(reflect.TypeOf(sec.v)) {
			fmt.Fprintf(&b, "        %s: '%s',\n", f, f)
		}
		b.WriteString("      },\n")
	}
	b.WriteString("    },\n")

	b.WriteString(`  };
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = NZ_CONTRACT;
  } else {
    root.NZ_CONTRACT = NZ_CONTRACT;
  }
})(this);
`)
	return b.String(), nil
}

// apiPaths reads the deduped, sorted /api/* paths from routes.golden.json.
func apiPaths(goldenPath string) ([]string, error) {
	data, err := os.ReadFile(goldenPath)
	if err != nil {
		return nil, fmt.Errorf("read routes golden: %w", err)
	}
	var routes []struct {
		Path string `json:"Path"`
	}
	if err := json.Unmarshal(data, &routes); err != nil {
		return nil, fmt.Errorf("parse routes golden: %w", err)
	}
	seen := map[string]bool{}
	var out []string
	for _, r := range routes {
		if !strings.HasPrefix(r.Path, "/api/") || seen[r.Path] {
			continue
		}
		seen[r.Path] = true
		out = append(out, r.Path)
	}
	sort.Strings(out)
	if len(out) == 0 {
		return nil, fmt.Errorf("no /api/ routes in %s", goldenPath)
	}
	return out, nil
}

// apiKey turns "/api/sessions/events" into "sessions_events" and
// "/api/memory/{slug}" into "memory_slug".
func apiKey(path string) string {
	k := strings.TrimPrefix(path, "/api/")
	k = strings.NewReplacer("/", "_", "{", "", "}", "", "-", "_", ".", "_").Replace(k)
	return k
}

// jsonFields returns the sorted json field names of t, inlining anonymous
// embedded structs the way encoding/json flattens them.
func jsonFields(t reflect.Type) []string {
	seen := map[string]bool{}
	var walk func(reflect.Type)
	walk = func(t reflect.Type) {
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			if f.Anonymous && f.Type.Kind() == reflect.Struct {
				walk(f.Type)
				continue
			}
			tag := f.Tag.Get("json")
			if tag == "" || tag == "-" {
				continue
			}
			name, _, _ := strings.Cut(tag, ",")
			seen[name] = true
		}
	}
	walk(t)
	out := make([]string, 0, len(seen))
	for n := range seen {
		out = append(out, n)
	}
	sort.Strings(out)
	return out
}
