// Package contractjs builds internal/server/static/contract.js — the
// generated frontend contract (#2539): WS message types (from wsproto), the
// /api/* route table (from the routes.golden.json snapshot TestRoutesSnapshot
// keeps in sync with registration) and the json field names of the dashboard
// export structs. The dashboard reads NZ_CONTRACT instead of re-typing
// backend literals, so a struct-tag or route change breaks a Go test, not
// production (#2432/#2433/#2476 class).
//
// It is an ES module the dashboard's modules import; the `@type {const}` cast
// and Object.freeze give tsc closed literal types. wire.d.ts (BuildWireDTS)
// types the payloads. tools/gen-contract writes both; the tests byte-compare
// each against its committed file, so a stale one fails CI.
package contractjs

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/naozhi/naozhi/internal/cli/clierr"
	"github.com/naozhi/naozhi/internal/cli/clievent"
	"github.com/naozhi/naozhi/internal/cliinfo"
	"github.com/naozhi/naozhi/internal/session"
	"github.com/naozhi/naozhi/internal/wsproto"
)

// Build renders contract.js. routesGoldenPath points at
// internal/server/testdata/routes.golden.json.
func Build(routesGoldenPath string) (string, error) {
	var b strings.Builder
	b.WriteString(`// Code generated by tools/gen-contract; DO NOT EDIT (#2539).
// An ES module: the dashboard's modules and the Node tooling import NZ_CONTRACT.
export const NZ_CONTRACT = Object.freeze(/** @type {const} */ ({
`)

	// WS: every browser message type, outbound and inbound.
	b.WriteString("  WS: {\n")
	types := make([]string, 0, len(wsproto.Frames))
	for typ := range wsproto.Frames {
		types = append(types, string(typ))
	}
	for _, typ := range []wsproto.MsgType{
		wsproto.TypeAuth, wsproto.TypeSubscribe, wsproto.TypeUnsubscribe,
		wsproto.TypeSend, wsproto.TypeInterrupt, wsproto.TypePing,
		wsproto.TypeAgentSubscribe, wsproto.TypeAgentUnsubscribe,
	} {
		types = append(types, string(typ))
	}
	sort.Strings(types)
	for _, typ := range types {
		fmt.Fprintf(&b, "    %s: '%s',\n", typ, typ)
	}
	b.WriteString("  },\n")

	// API: the /api/* route paths from the tested route snapshot.
	paths, err := apiPaths(routesGoldenPath)
	if err != nil {
		return "", err
	}
	b.WriteString("  API: {\n")
	for _, p := range paths {
		fmt.Fprintf(&b, "    %s: '%s',\n", apiKey(p), p)
	}
	b.WriteString("  },\n")

	// ENUMS: wire vocabularies the dashboard reads instead of restating each
	// member as a literal (#2909 G5); the EVENT_TYPE lists are clievent's
	// kindTable columns (S13b-4). SESSION_STATE is not yet enforced against
	// literal comparisons — see the PR for why.
	deathReasons := append([]string{}, cliinfo.AllDeathReasons()...)
	deathReasons = append(deathReasons, session.DeathReasonIdleTimeout, session.DeathReasonEvicted, session.DeathReasonReleased)
	sort.Strings(deathReasons)
	b.WriteString("  ENUMS: {\n")
	writeEnum(&b, "DEATH_REASON", deathReasons)
	writeEnum(&b, "SESSION_STATE", cliinfo.AllSessionStates())
	writeEnum(&b, "EVENT_TYPE", clievent.AllKinds())
	writeEnum(&b, "EVENT_TYPE_INTERNAL", clievent.InternalKinds())
	writeEnum(&b, "EVENT_TYPE_NO_BUBBLE", clievent.NoBubbleKinds())
	writeEnum(&b, "EVENT_TYPE_MD_IGNORE", clievent.MarkdownIgnoreKinds())
	writeEnum(&b, "STARTUP_FAILURE_CLASS", clierr.AllExitClassWires())
	b.WriteString("  },\n")

	// DEATH_REASON_PREFIX: the shapes of a cli_exited reason that carries an
	// exit code or a signal name, so the dashboard can name either.
	fmt.Fprintf(&b, "  DEATH_REASON_PREFIX: { CODE: '%s', SIGNAL: '%s' },\n",
		cliinfo.DeathReasonCLIExitedCodePrefix, cliinfo.DeathReasonCLIExitedSignalPrefix)

	b.WriteString("}));\n")
	return b.String(), nil
}

// writeEnum writes one ENUMS line: `    NAME: ['a', 'b'],`.
func writeEnum(b *strings.Builder, name string, values []string) {
	fmt.Fprintf(b, "    %s: [", name)
	for i, v := range values {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "'%s'", v)
	}
	b.WriteString("],\n")
}

// apiPaths reads the deduped, sorted /api/* paths from routes.golden.json.
func apiPaths(goldenPath string) ([]string, error) {
	data, err := os.ReadFile(goldenPath)
	if err != nil {
		return nil, fmt.Errorf("read routes golden: %w", err)
	}
	var routes []struct {
		Path string `json:"Path"`
	}
	if err := json.Unmarshal(data, &routes); err != nil {
		return nil, fmt.Errorf("parse routes golden: %w", err)
	}
	seen := map[string]bool{}
	var out []string
	for _, r := range routes {
		if !strings.HasPrefix(r.Path, "/api/") || seen[r.Path] {
			continue
		}
		seen[r.Path] = true
		out = append(out, r.Path)
	}
	sort.Strings(out)
	if len(out) == 0 {
		return nil, fmt.Errorf("no /api/ routes in %s", goldenPath)
	}
	return out, nil
}

// apiKey turns "/api/sessions/events" into "sessions_events" and
// "/api/memory/{slug}" into "memory_slug".
func apiKey(path string) string {
	k := strings.TrimPrefix(path, "/api/")
	k = strings.NewReplacer("/", "_", "{", "", "}", "", "-", "_", ".", "_").Replace(k)
	return k
}
