package contractjs

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"reflect"
	"sort"
	"strings"
)

// wire.d.ts is the typing half of the contract (#3439): the payload shapes
// from the two committed schema files, as global declarations tsc --checkJs
// reads through internal/server/static/tsconfig.json. The browser never
// loads it (static_assets.go embeds file by file).

type schemaFile struct {
	Types     []string                `json:"types"`
	Frames    map[string]schemaObject `json:"frames"`
	Responses map[string]schemaObject `json:"responses"`
	Defs      map[string]schemaObject `json:"defs"`
}

type schemaObject struct {
	Properties map[string]schemaProp `json:"properties"`
	Required   []string              `json:"required"`
}

type schemaProp struct {
	Type  string      `json:"type"`
	Ref   string      `json:"$ref"`
	Items *schemaProp `json:"items"`
	Enum  []string    `json:"enum"`
}

// BuildWireDTS renders wire.d.ts: one global interface per schema def, named
// by its Go type name without the package (so `@type {EventEntry}` resolves),
// a WsFrame_<type> per WS frame with `type` pinned to its literal, a
// RestResponse_<name> per REST response, and the WsFrames / RestResponses
// maps that wsm.on and the fetch call sites index.
func BuildWireDTS(wsSchemaPath, restSchemaPath string) (string, error) {
	ws, err := readSchema(wsSchemaPath)
	if err != nil {
		return "", err
	}
	rest, err := readSchema(restSchemaPath)
	if err != nil {
		return "", err
	}

	defs := map[string]schemaObject{}
	for _, s := range []schemaFile{ws, rest} {
		for full, obj := range s.Defs {
			if prev, ok := defs[full]; ok && !reflect.DeepEqual(prev, obj) {
				return "", fmt.Errorf("def %s differs between the WS and REST schemas", full)
			}
			defs[full] = obj
		}
	}
	short := map[string]string{} // full def name -> interface name
	owner := map[string]string{} // interface name -> full def name
	for full := range defs {
		name := full[strings.LastIndex(full, ".")+1:]
		if other, ok := owner[name]; ok {
			return "", fmt.Errorf("defs %s and %s share the short name %s", other, full, name)
		}
		owner[name] = full
		short[full] = name
	}

	var b strings.Builder
	b.WriteString("// Code generated by tools/gen-contract from wsproto.schema.json and rest.schema.json; DO NOT EDIT (#3439).\n")
	b.WriteString("// Global types for tsc --checkJs (tsconfig.json beside it); never served.\n")
	b.WriteString("export {};\n\ndeclare global {\n")

	for _, name := range sortedKeys(owner) {
		if err := writeInterface(&b, name, defs[owner[name]], short, ""); err != nil {
			return "", fmt.Errorf("def %s: %w", owner[name], err)
		}
	}

	frames := sortedKeys(ws.Frames)
	if !reflect.DeepEqual(frames, sortedCopy(ws.Types)) {
		return "", fmt.Errorf("wsproto schema: types %v do not match frames %v", ws.Types, frames)
	}
	for _, typ := range frames {
		if err := writeInterface(&b, "WsFrame_"+typ, ws.Frames[typ], short, typ); err != nil {
			return "", fmt.Errorf("frame %s: %w", typ, err)
		}
	}
	b.WriteString("  interface WsFrames {\n")
	for _, typ := range frames {
		fmt.Fprintf(&b, "    %s: WsFrame_%s;\n", tsKey(typ), typ)
	}
	b.WriteString("  }\n")

	responses := sortedKeys(rest.Responses)
	for _, name := range responses {
		if err := writeInterface(&b, "RestResponse_"+name, rest.Responses[name], short, ""); err != nil {
			return "", fmt.Errorf("response %s: %w", name, err)
		}
	}
	b.WriteString("  interface RestResponses {\n")
	for _, name := range responses {
		fmt.Fprintf(&b, "    %s: RestResponse_%s;\n", tsKey(name), name)
	}
	b.WriteString("  }\n}\n")
	return b.String(), nil
}

func readSchema(path string) (schemaFile, error) {
	var s schemaFile
	data, err := os.ReadFile(path)
	if err != nil {
		return s, fmt.Errorf("read schema: %w", err)
	}
	// A keyword this decoder does not model (oneOf, nullable, ...) is an
	// error: dropping it would render a type that silently loses the rule.
	dec := json.NewDecoder(bytes.NewReader(data))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&s); err != nil {
		return s, fmt.Errorf("parse %s: %w", path, err)
	}
	return s, nil
}

// writeInterface renders obj as `interface name { ... }`; keys outside
// Required are optional. A non-empty frameType pins the `type` key to it.
func writeInterface(b *strings.Builder, name string, obj schemaObject, short map[string]string, frameType string) error {
	required := map[string]bool{}
	for _, r := range obj.Required {
		required[r] = true
	}
	fmt.Fprintf(b, "  interface %s {\n", name)
	if frameType != "" {
		if !required["type"] {
			return fmt.Errorf("no required type key")
		}
		fmt.Fprintf(b, "    type: %s;\n", tsString(frameType))
	}
	for _, key := range sortedKeys(obj.Properties) {
		if frameType != "" && key == "type" {
			continue
		}
		t, err := tsType(obj.Properties[key], short)
		if err != nil {
			return fmt.Errorf("%s: %w", key, err)
		}
		opt := "?"
		if required[key] {
			opt = ""
		}
		fmt.Fprintf(b, "    %s%s: %s;\n", tsKey(key), opt, t)
	}
	b.WriteString("  }\n")
	return nil
}

// tsType maps a schema property to a TypeScript type expression.
func tsType(p schemaProp, short map[string]string) (string, error) {
	if p.Ref != "" {
		name, ok := short[p.Ref]
		if !ok {
			return "", fmt.Errorf("$ref %s names no def", p.Ref)
		}
		return name, nil
	}
	if len(p.Enum) > 0 {
		parts := make([]string, len(p.Enum))
		for i, v := range p.Enum {
			parts[i] = tsString(v)
		}
		return strings.Join(parts, " | "), nil
	}
	switch p.Type {
	case "string":
		return "string", nil
	case "boolean":
		return "boolean", nil
	case "integer", "number":
		return "number", nil
	case "any":
		return "unknown", nil
	case "object":
		return "Record<string, unknown>", nil
	case "array":
		if p.Items == nil {
			return "unknown[]", nil
		}
		el, err := tsType(*p.Items, short)
		if err != nil {
			return "", err
		}
		if strings.Contains(el, " | ") {
			el = "(" + el + ")"
		}
		return el + "[]", nil
	}
	return "", fmt.Errorf("unmapped schema type %q", p.Type)
}

// tsKey quotes a property name that is not a plain identifier.
func tsKey(k string) string {
	for i, r := range k {
		if !(r == '_' || r == '$' || 'a' <= r && r <= 'z' || 'A' <= r && r <= 'Z' || i > 0 && '0' <= r && r <= '9') {
			return tsString(k)
		}
	}
	if k == "" {
		return "''"
	}
	return k
}

func tsString(s string) string {
	return "'" + strings.NewReplacer(`\`, `\\`, `'`, `\'`, "\n", `\n`).Replace(s) + "'"
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func sortedCopy(s []string) []string {
	out := append([]string{}, s...)
	sort.Strings(out)
	return out
}
